(function(){
'use strict';
function resolvePath(plugin,path){if(!path)return '';if(/^(https?:|data:|blob:|file:|plugins\/)/i.test(path))return path;const folder=String(plugin.folder||plugin.id||'').replace(/^plugins\//,'').replace(/\/$/,'');return `plugins/${folder}/${String(path).replace(/^\//,'')}`;}
function renderedContainRect(img,frame){const fr=frame.getBoundingClientRect(),nw=img.naturalWidth||1,nh=img.naturalHeight||1,scale=Math.min(fr.width/nw,fr.height/nh),width=nw*scale,height=nh*scale;return{left:(fr.width-width)/2,top:(fr.height-height)/2,width,height};}
function center(record){const b=record.config.bounds||{};return{x:Number(b.x||0)+Number(b.width||10)/2,y:Number(b.y||0)+Number(b.height||10)/2};}
function nearest(records,current,key){const c=center(records[current]),direction={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[key];let best=-1,score=Infinity;records.forEach((r,i)=>{if(i===current)return;const p=center(r),dx=p.x-c.x,dy=p.y-c.y;if(dx*direction[0]+dy*direction[1]<=0)return;const primary=Math.abs(direction[0]?dx:dy),secondary=Math.abs(direction[0]?dy:dx),s=primary+secondary*2.25;if(s<score){score=s;best=i;}});return best;}
function makePracticeCue(options){
 const Cue=window.PrismPracticeCue;
 if(typeof Cue==='function'){try{return new Cue(options);}catch(error){console.error('Prism PracticeCue init failed',error);}}
 return {enabled:false,config:{enabled:false,trigger:'afterAudio'},update(){return this;},show(){},hide(){},destroy(){}};
}
class InteractiveHotspots{
 constructor(ctx){this.ctx=ctx;this.plugin=ctx.plugin;this.records=[];this.selected=-1;this.practice=null;this.zoom=1;this.panX=0;this.panY=0;this.zoomPointers=new Map();this.lastTap=0;this.keyHandler=e=>this.onKey(e);this.resizeHandler=()=>{this.layout();this.practiceCue?.layout?.();};}
 async mount(){
  if(this.plugin.scenes&&!this.plugin.__sceneId)return window.PrismMountNavigablePlugin(this.ctx);
  const p=this.plugin,image=resolvePath(p,p.backgroundImage||p.image||''),blur=p.display?.blurBackground===true||p.scene?.blurBackground===true;
  this.root=document.createElement('div');this.root.className='prism-interaction-host prism-interactive-hotspots';this.root.dataset.pluginId=p.id||'';const sceneFx=p.sceneEffects||p.effects?.scene||[];(Array.isArray(sceneFx)?sceneFx:[sceneFx]).filter(Boolean).forEach(name=>this.root.classList.add(`scene-fx-${name}`));
  this.root.innerHTML=`<div class="prism-scene-frame ${blur?'has-blurred-background':''}">${blur&&image?`<div class="prism-scene-blur" style="background-image:url('${image.replace(/'/g,"\\'")}')"></div>`:''}<img class="prism-scene-image" src="${image}" alt="${p.title||''}"><div class="prism-scene-layer"></div></div>${this.ctx.navigator?'<button type="button" class="prism-scene-back" aria-label="Back to habitats"><b class="prism-back-arrow">↩</b><span class="prism-habitat-label"><i>🐾</i> Habitats <i>🐾</i></span></button>':''}<div class="prism-practice-panel" hidden><button data-act="previous">‹ Previous</button><button data-act="repeat">↻ Again</button><button data-act="next">Next ›</button></div>`;
  this.ctx.host.appendChild(this.root);this.root.querySelector('.prism-scene-back')?.addEventListener('click',()=>this.ctx.navigator?.back());this.frame=this.root.querySelector('.prism-scene-frame');this.img=this.root.querySelector('.prism-scene-image');this.layer=this.root.querySelector('.prism-scene-layer');this.panel=this.root.querySelector('.prism-practice-panel');this.audio=new Audio();this.audio.preload='auto';this.build();this.practiceCue=makePracticeCue({host:this.root,plugin:p,onEnabledChange:(enabled,config)=>{if(this.practice){this.practice.setCueEnabled(enabled);this.practice.setCueTrigger(config.trigger);}}});this.audioEndedHandler=()=>{const t=this.practiceCue?.config?.trigger;const triggers=new Set(Array.isArray(t)?t:String(t||'').split(/[\s,|]+/));if(!this.audio.loop&&this.practiceCue?.enabled&&(triggers.has('afterAudio')||triggers.has('auto')))this.practiceCue.show();};this.audio.addEventListener('ended',this.audioEndedHandler);this.bindZoom();
  this.panel.addEventListener('click',e=>{const a=e.target?.dataset?.act;if(a)this.action(a);});this.img.addEventListener('load',this.resizeHandler);window.addEventListener('resize',this.resizeHandler);window.addEventListener('orientationchange',this.resizeHandler);document.addEventListener('keydown',this.keyHandler,true);if(this.img.complete)this.layout();this.ctx.setFocusable?.(this.root);return this;
 }

 bindZoom(){
  const z=this.plugin.zoom||this.plugin.display?.zoom;if(!z?.enabled||!this.frame)return;
  this.root.classList.add('is-zoom-enabled');
  const min=Number(z.min||1),max=Number(z.max||3),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const apply=()=>{if(this.zoom<=min+.001){this.zoom=min;this.panX=this.panY=0;}const t=`translate3d(${this.panX}px,${this.panY}px,0) scale(${this.zoom})`;this.img.style.transform=t;this.layer.style.transform=t;this.img.style.transformOrigin='50% 50%';this.layer.style.transformOrigin='50% 50%';this.root.classList.toggle('is-zoomed',this.zoom>min+.01);};
  const reset=()=>{this.zoom=min;this.panX=this.panY=0;apply();};this.resetZoom=reset;
  const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});

  // Android/WebView path: capture-phase Touch Events prevent parent swipe handlers
  // from consuming the second finger before the habitat viewer sees it.
  let touchGesture=null,touchMoved=false,lastTouchTap=0;
  const touchPoints=e=>Array.from(e.touches||[]).map(t=>({x:t.clientX,y:t.clientY}));
  const beginTouch=e=>{
   if(e.target.closest?.('.prism-scene-back'))return;
   const pts=touchPoints(e);touchMoved=false;
   if(pts.length>=2&&z.pinch!==false){e.preventDefault();e.stopPropagation();const m=mid(pts[0],pts[1]);touchGesture={kind:'pinch',distance:Math.max(1,dist(pts[0],pts[1])),zoom:this.zoom,mid:m,panX:this.panX,panY:this.panY};}
   else if(pts.length===1){touchGesture={kind:'pan',start:pts[0],panX:this.panX,panY:this.panY};}
  };
  const moveTouch=e=>{
   const pts=touchPoints(e);
   if(pts.length>=2&&z.pinch!==false){e.preventDefault();e.stopPropagation();touchMoved=true;if(!touchGesture||touchGesture.kind!=='pinch'){const m=mid(pts[0],pts[1]);touchGesture={kind:'pinch',distance:Math.max(1,dist(pts[0],pts[1])),zoom:this.zoom,mid:m,panX:this.panX,panY:this.panY};return;}const m=mid(pts[0],pts[1]);this.zoom=clamp(touchGesture.zoom*(dist(pts[0],pts[1])/touchGesture.distance),min,max);this.panX=touchGesture.panX+(m.x-touchGesture.mid.x);this.panY=touchGesture.panY+(m.y-touchGesture.mid.y);apply();return;}
   if(pts.length===1&&touchGesture?.kind==='pan'&&this.zoom>min+.01&&z.pan!==false){e.preventDefault();e.stopPropagation();const dx=pts[0].x-touchGesture.start.x,dy=pts[0].y-touchGesture.start.y;if(Math.abs(dx)>2||Math.abs(dy)>2)touchMoved=true;this.panX=touchGesture.panX+dx;this.panY=touchGesture.panY+dy;apply();}
  };
  const endTouch=e=>{
   const pts=touchPoints(e);
   if(pts.length===1){touchGesture={kind:'pan',start:pts[0],panX:this.panX,panY:this.panY};return;}
   if(pts.length===0){const now=performance.now();if(!touchMoved&&z.doubleTapReset!==false){if(now-lastTouchTap<340){if(this.zoom>min+.01)reset();else{this.zoom=Math.min(max,2);apply();}lastTouchTap=0;}else lastTouchTap=now;}touchGesture=null;}
  };
  this.zoomTouchStart=beginTouch;this.zoomTouchMove=moveTouch;this.zoomTouchEnd=endTouch;

  // Pointer path remains for desktop, pens and browsers that do not expose Touch Events.
  let points=new Map(),pointerGesture=null,pointerMoved=false,lastPointerTap=0;
  const beginPointerGesture=()=>{const a=[...points.values()];if(a.length>=2){const m=mid(a[0],a[1]);pointerGesture={kind:'pinch',distance:Math.max(1,dist(a[0],a[1])),zoom:this.zoom,mid:m,panX:this.panX,panY:this.panY};}else if(a.length===1){pointerGesture={kind:'pan',start:a[0],panX:this.panX,panY:this.panY};}else pointerGesture=null;};
  this.zoomPointerDown=e=>{if(('ontouchstart' in window)&&e.pointerType==='touch')return;if(e.target.closest?.('.prism-scene-back'))return;if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});pointerMoved=false;try{this.frame.setPointerCapture?.(e.pointerId);}catch(_){};beginPointerGesture();};
  this.zoomPointerMove=e=>{if(!points.has(e.pointerId))return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});const a=[...points.values()];if(a.length>=2&&z.pinch!==false){e.preventDefault();pointerMoved=true;if(!pointerGesture||pointerGesture.kind!=='pinch')beginPointerGesture();const m=mid(a[0],a[1]);this.zoom=clamp(pointerGesture.zoom*(dist(a[0],a[1])/pointerGesture.distance),min,max);this.panX=pointerGesture.panX+(m.x-pointerGesture.mid.x);this.panY=pointerGesture.panY+(m.y-pointerGesture.mid.y);apply();}else if(a.length===1&&pointerGesture?.kind==='pan'&&this.zoom>min+.01&&z.pan!==false){e.preventDefault();const dx=a[0].x-pointerGesture.start.x,dy=a[0].y-pointerGesture.start.y;if(Math.abs(dx)>2||Math.abs(dy)>2)pointerMoved=true;this.panX=pointerGesture.panX+dx;this.panY=pointerGesture.panY+dy;apply();}};
  this.zoomPointerUp=e=>{if(!points.has(e.pointerId))return;points.delete(e.pointerId);try{this.frame.releasePointerCapture?.(e.pointerId);}catch(_){};if(points.size){beginPointerGesture();return;}const now=performance.now();if(!pointerMoved&&e.pointerType!=='mouse'&&z.doubleTapReset!==false){if(now-lastPointerTap<340){if(this.zoom>min+.01)reset();else{this.zoom=Math.min(max,2);apply();}lastPointerTap=0;}else lastPointerTap=now;}pointerGesture=null;};
  this.zoomWheel=e=>{if(z.wheel===false)return;e.preventDefault();this.zoom=clamp(this.zoom*(e.deltaY<0?1.13:.885),min,max);apply();};
  this.zoomDblClick=e=>{if(z.doubleTapReset!==false){e.preventDefault();if(this.zoom>min+.01)reset();else{this.zoom=Math.min(max,2);apply();}}};
  this.frame.style.touchAction='none';this.img.style.touchAction='none';this.layer.style.touchAction='none';
  this.frame.addEventListener('touchstart',this.zoomTouchStart,{passive:false,capture:true});
  this.frame.addEventListener('touchmove',this.zoomTouchMove,{passive:false,capture:true});
  this.frame.addEventListener('touchend',this.zoomTouchEnd,{passive:false,capture:true});
  this.frame.addEventListener('touchcancel',this.zoomTouchEnd,{passive:false,capture:true});
  this.frame.addEventListener('pointerdown',this.zoomPointerDown,{passive:false,capture:true});
  this.frame.addEventListener('pointermove',this.zoomPointerMove,{passive:false,capture:true});
  this.frame.addEventListener('pointerup',this.zoomPointerUp,{passive:false,capture:true});
  this.frame.addEventListener('pointercancel',this.zoomPointerUp,{passive:false,capture:true});
  this.frame.addEventListener('wheel',this.zoomWheel,{passive:false});this.frame.addEventListener('dblclick',this.zoomDblClick);
 }
 build(){(this.plugin.entities||[]).forEach((it,i)=>{const el=document.createElement('button');el.type='button';el.className=`prism-hotspot effect-${it.effect||'scaleGlow'}`;el.setAttribute('aria-label',it.name||it.id||`Item ${i+1}`);el.addEventListener('click',()=>this.activate(i,true));this.layer.appendChild(el);this.records.push({config:it,el});});}
 layout(){if(!this.img?.naturalWidth||!this.frame)return;const r=renderedContainRect(this.img,this.frame);this.layer.style.left=r.left+'px';this.layer.style.top=r.top+'px';this.layer.style.width=r.width+'px';this.layer.style.height=r.height+'px';this.records.forEach(({config,el})=>{const b=config.bounds||{};el.style.left=Number(b.x||0)+'%';el.style.top=Number(b.y||0)+'%';el.style.width=Number(b.width||10)+'%';el.style.height=Number(b.height||10)+'%';});this.practiceCue?.layout?.();}
 async activate(i,user){if(i<0||i>=this.records.length)return;this.selected=i;this.records.forEach((r,n)=>r.el.classList.toggle('is-focused',n===i));const it=this.records[i].config;if(it.targetScene&&this.ctx.navigator){await this.ctx.navigator.go(it.targetScene);return;}this.practice?.stop();this.practice=null;const audio=resolvePath(this.plugin,it.audio);if(audio)this.audio.src=audio;this.practiceCue.update(it).anchorTo?.(rec.el);if(it.segmentsFile&&it.practice?.enabled!==false){this.practice=new window.PrismPracticeController({audio:this.audio,cueEnabled:this.practiceCue.enabled,cueTrigger:this.practiceCue.config.trigger,onDecision:()=>this.panel.hidden=false,onDecisionEnd:()=>this.panel.hidden=true,onYourTurn:(v,ms)=>v?this.practiceCue.show(ms):this.practiceCue.hide(),onIndexChange:n=>this.saveProgress(it,n)});try{await this.practice.load(resolvePath(this.plugin,it.segmentsFile));this.practice.setIndex(this.loadProgress(it));}catch(e){}}if(user)this.playSelected();}
 playSelected(){if(this.selected<0)return;this.practiceCue?.hide();const rec=this.records[this.selected],it=rec.config;rec.el.classList.remove('is-active');void rec.el.offsetWidth;rec.el.classList.add('is-active');setTimeout(()=>rec.el.classList.remove('is-active'),Number(it.effectDurationMs)||1800);const mode=this.ctx.getMode?.()||'listen';if(this.practice){if(mode==='repeat5')return this.practice.repeatCurrent(it.practice?.repeatCount||5);if(mode==='hifz')return this.practice.runHifz();if(mode==='learnListen')return this.practice.playCurrentOnce();return this.practice.playFull(this.ctx.isLoop?.()||false);}if(this.audio.src){this.audio.loop=this.ctx.isLoop?.()||false;this.audio.currentTime=0;this.audio.play().catch(()=>{});}}
 action(a){if(!this.practice)return;const mode=this.ctx.getMode?.()||'repeat5';if(a==='repeat')this.practice.repeatAgain(mode);if(a==='next')this.practice.next(mode);if(a==='previous')this.practice.previous(mode);}saveProgress(it,n){try{localStorage.setItem(`prism:${this.plugin.id}:${it.id}:segment`,String(n));}catch(e){}}loadProgress(it){try{return Number(localStorage.getItem(`prism:${this.plugin.id}:${it.id}:segment`))||0;}catch(e){return 0;}}
 onKey(e){if(!this.ctx.isActive?.())return;if((e.key==='Escape'||e.key==='Backspace'||e.key==='BrowserBack')&&this.ctx.navigator){e.preventDefault();this.ctx.navigator.back();return;}if(this.practice?.waiting){if(e.key==='Enter'||e.key==='OK'){e.preventDefault();this.action('repeat');return;}if(e.key==='ArrowRight'){e.preventDefault();this.action('next');return;}if(e.key==='ArrowLeft'){e.preventDefault();this.action('previous');return;}}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();let next=-1;if(this.selected>=0){const explicit=this.records[this.selected].config.navigation?.[e.key.replace('Arrow','').toLowerCase()];if(explicit)next=this.records.findIndex(r=>r.config.id===explicit);if(next<0)next=nearest(this.records,this.selected,e.key);}else next=0;if(next>=0){this.activate(next,false);this.records[next].el.focus();}}if((e.key==='Enter'||e.key==='OK')&&this.selected>=0){e.preventDefault();this.activate(this.selected,true);}}
 onModeChange(){if(this.selected>=0)this.playSelected();}onLoopChange(){this.audio.loop=this.ctx.isLoop?.()||false;}stop(){this.practice?.stop();this.audio.pause();this.panel.hidden=true;this.practiceCue?.hide();}destroy(){this.stop();this.resetZoom?.();this.audio?.removeEventListener('ended',this.audioEndedHandler);this.frame?.removeEventListener('pointerdown',this.zoomPointerDown,true);this.frame?.removeEventListener('pointermove',this.zoomPointerMove,true);this.frame?.removeEventListener('pointerup',this.zoomPointerUp,true);this.frame?.removeEventListener('pointercancel',this.zoomPointerUp,true);this.frame?.removeEventListener('wheel',this.zoomWheel);this.frame?.removeEventListener('dblclick',this.zoomDblClick);this.frame?.removeEventListener('touchstart',this.zoomTouchStart,true);this.frame?.removeEventListener('touchmove',this.zoomTouchMove,true);this.frame?.removeEventListener('touchend',this.zoomTouchEnd,true);this.frame?.removeEventListener('touchcancel',this.zoomTouchEnd,true);this.practiceCue?.destroy();document.removeEventListener('keydown',this.keyHandler,true);window.removeEventListener('resize',this.resizeHandler);window.removeEventListener('orientationchange',this.resizeHandler);this.root?.remove();}
}
window.PrismEngines=window.PrismEngines||{};window.PrismEngines.interactiveHotspots={mount:ctx=>new InteractiveHotspots(ctx).mount()};
})();
