(function(){
'use strict';
function n(v,d){v=Number(v);return Number.isFinite(v)?v:d;}
function clearRecord(r){['left','top','width','height','opacity','transform','zIndex'].forEach(k=>r.el.style[k]='');}
function clearLayout(root,records){root.classList.remove('prism-layout-carousel3d','prism-layout-orbit');records.forEach(clearRecord);}
function applyCarousel3D(root,records,selected,cfg){clearLayout(root,records);root.classList.add('prism-layout-carousel3d');const count=records.length,active=selected<0?0:selected,spacing=n(cfg.spacingPercent,25),sideOpacity=n(cfg.sideOpacity,.45),sideScale=n(cfg.sideScale,.86),centerScale=n(cfg.centerScale,1.08),angle=n(cfg.sideAngleDeg,18);records.forEach((r,i)=>{let delta=i-active;if(cfg.loop){if(delta>count/2)delta-=count;if(delta<-count/2)delta+=count;}const distance=Math.abs(delta),scale=distance===0?centerScale:Math.max(sideScale-.04*Math.max(0,distance-1),.68),opacity=distance===0?1:Math.max(sideOpacity-.12*Math.max(0,distance-1),.18);r.el.style.left='50%';r.el.style.top='50%';r.el.style.width=cfg.itemWidth||'min(30vw,320px)';r.el.style.height=cfg.itemHeight||'min(48vh,380px)';r.el.style.opacity=String(opacity);r.el.style.transform=`translate(calc(-50% + ${delta*spacing}vw),-50%) perspective(900px) rotateY(${delta*-angle}deg) scale(${scale})`;r.el.style.zIndex=String(100-distance);});}
function applyOrbit(root,records,selected,cfg){clearLayout(root,records);root.classList.add('prism-layout-orbit');const total=Math.max(1,records.length),offset=selected<0?0:selected,rx=n(cfg.radiusX,34),ry=n(cfg.radiusY,27);records.forEach((r,i)=>{const angle=((i-offset)/total)*Math.PI*2-Math.PI/2,x=50+Math.cos(angle)*rx,y=50+Math.sin(angle)*ry,depth=(Math.sin(angle)+1)/2;r.el.style.left=`${x}%`;r.el.style.top=`${y}%`;r.el.style.width=cfg.itemWidth||'min(20vw,220px)';r.el.style.height=cfg.itemHeight||'min(30vh,260px)';r.el.style.transform=`translate(-50%,-50%) scale(${.78+depth*.25})`;r.el.style.opacity=String(.55+depth*.45);r.el.style.zIndex=String(Math.round(5+depth*10));});}
window.PrismSelectableLayouts={apply(root,records,selected,cfg){const type=cfg?.type||'static';if(type==='carousel3D')return applyCarousel3D(root,records,selected,cfg);if(type==='orbit')return applyOrbit(root,records,selected,cfg);clearLayout(root,records);}};
})();
